name: combos
description: Combo Widgets for Flutter. Includes Combo, AwaitCombo, ListCombo, SelectorCombo, TypeaheadCombo, MenuItemCombo
version: 1.2.0
homepage: https://github.com/creomobile/combos

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_platform: ^3.0.1

dev_dependencies:
  pedantic: ^1.8.0

flutter:
